### ISSUE TITLE
有考虑为Js标签格式化提供是否添加/移除分号的选项吗？

### ISSUE THREAD

**Issue by yihuishou** [win7killer/vue-format#13]
**Describe the bug** [描述]

如题 0.0 ，希望能提供格式化的选项

**Comment by win7killer** [comment]
@yihuishou  这个貌似 “js-beautify” 没有提供，暂时不会提供。
如果之后有提供，会在这里同步给你。

**Comment by yihuishou** [comment]
感谢~
