### ISSUE TITLE
很喜欢这一套格式化的结果.能不能再优化下呢

### ISSUE THREAD

**Issue by lifetin** [win7killer/vue-format#14]
很喜欢这一套格式化的结果.能不能再优化下呢
比喻ctrl+shift+F默认就把vue给式化了, 如果能用这个格式化独立的HTML,JS,CSS这样更好了. 免得再又配置其它的文件独立格式化.

**Comment by lifetin** [comment]
这个可以默认关联上vue的文件
{
        "key": "ctrl+shift+f",
        "command": "extension.vueFormat",
        "when": "editorTextFocus && editorLangId == 'vue'" 
    }

**Comment by win7killer** [comment]
@lifetin 
- 单独格式化 html,css,js   可以考虑使用后  “beautify” 插件，我现在也在用。成熟，下载量大。
- 快捷键这个下个版本会提上日程

**Comment by lifetin** [comment]
目前用了beautify,但是不太理想,和你这个格式化的结果不一样,也不太会手动配置的了. 要一个个的试.
觉得你这个比较符合个人强追症

**Comment by win7killer** [comment]
@lifetin  快捷键已在 v1.0.7 中支持。   alt[cmd] + ctrl + p
