### ISSUE TITLE
格式化<span>标签的时候不正确, 尤其是<span>下有<div>标签的时候。

### ISSUE THREAD

**Issue by ZwPandora** [win7killer/vue-format#18]
<span slot="title">
          <div class="dialog-title">
            <div>
              <img />
              <span style="color:#409eff"></span>
      <span></span>
  </div>
  </div>
  </span>
  <span slot="title">
          <div class="create-dialog-title">
            <div class="create-market-no">
              <img src=>
              <span></span>
  <span></span>
  </div>
  <div class="create-market-title"></div>
  </div>
  </span>

**Comment by win7killer** [comment]
fixed in v1.0.7, update please
