### ISSUE TITLE
格式化自动在template script style之间加空行，即使原来已存在空行

### ISSUE THREAD

**Issue by wpycs** [win7killer/vue-format#2]
**Describe the bug** [描述]
格式化自动在template script style之间加空行，即使原来已存在空行

**To Reproduce**[复现]
创建空vue文件，输入template，script ，style节点
格式化文件，每格式化一次三个标签都会加一行空行

**Desktop (please complete the following information):**[环境]
 - OS:Windows10
 - Version VsCode 1.23  1.24

**Comment by win7killer** [comment]
@wpycs  等我抽空找个windows 环境先看下

**Comment by wpycs** [comment]
thx,已解决
