### ISSUE TITLE
能不能根据编辑器语言进行中英文菜单自适应显示？

### ISSUE THREAD

**Issue by yihuishou** [win7killer/vue-format#4]
强迫症待拯救 QAQ

**Comment by win7killer** [comment]
@yihuishou   是说"vue format"指令名称？

**Comment by yihuishou** [comment]
是滴 全中文菜单里一条英文。

**Comment by win7killer** [comment]
@yihuishou   
这个是配置在package.json中的配置项，没办法做变量处理，官方也没有提供相关翻译用的配置项；然后编辑器所谓语言设置，只是你安装的中文汉化plugin，这个标识也只能在代码中用已有插件判断。

结论：目前搞不了  ┓( ´∀` )┏

**Comment by win7killer** [comment]
#
