### ISSUE TITLE
template functional attribute removed

### ISSUE THREAD

**Issue by cyoharry** [win7killer/vue-format#6]
**Describe the bug** [描述]
Format removes `functional` from <template functional></template>

**To Reproduce**[复现]
- create a new `.vue` file.
- Add `<template functional><p></p></template>`
- Format

**Expected behavior**[预期]
the functional attribute should be left in place. Otherwise I have to add a script block and include the functional setting there causing bloat.

**Comment by win7killer** [comment]
@cyoharry 
It has been fixed in version 0.1.3
