### ISSUE TITLE
css为什么不弄单行样式呢?

### ISSUE THREAD

**Issue by lifetin** [win7killer/vue-format#8]
不太会js-beautify设置,

**Comment by win7killer** [comment]
@lifetin   单行样式是指什么？给个例子

**Comment by win7killer** [comment]
need more info

**Comment by lifetin** [comment]
![55](https://user-images.githubusercontent.com/10474968/49197604-68ae5900-f3ca-11e8-8e29-91661478be56.png)
这 样就是单行了

**Comment by win7killer** [comment]
@lifetin 
- 多选择器的单行，js-beautify 里边实际上有对应配置项的，但是貌似有问题，断行后的并未处理。**下个版本我会自己处理这个问题**；
- 关于里边多样式单行展示，这个 js-beautify 没有，我这边也不打算支持。因为1.难看；2.不符合 css 代码规范。估计你不写 less 或者 sass ，如果用嵌套的话，你会发现单行根本没法看。

**Comment by lifetin** [comment]
最好是能把他能应用到JS,HTML,CSS中去.
既然他能格式化出VUE中的3种代码, 理论上说他也能格式化CSS,JS,HTML文件的了.
这样就不用去配置别的格式化扩展了.

另外希望默认VUE文件用这个来格式化. 目前是手动设置的
{
        "key": "ctrl+shift+f",
        "command": "extension.vueFormat",
        "when": "editorTextFocus &&  editorLangId == 'vue' "
    }
